set(SOCKET_HEADERS
    include/socket/protocols/AuthorizingProtocol.h
    include/socket/protocols/AuthRequiredProtocol.h
    include/socket/protocols/PingingProtocol.h
    include/socket/protocols/PongingProtocol.h
    include/socket/protocols/ProtocolBase.h
    include/socket/protocols/ProtocolDecorator.h
    include/socket/protocols/ProtocolWithRequests.h
    include/socket/sessions/SessionBase.h
    include/socket/sessions/SSLSession.h
    include/socket/AsyncServer.h
    include/socket/BoostIOContext.h
    include/socket/BoostSSLContext.h
    include/socket/byte_order.h
    include/socket/connection_protocol.h
    include/socket/ConnectionHandler.hpp
    include/socket/ConnectionStorage.h
    include/socket/Protocol.hpp
    include/socket/Session.hpp
    include/socket/SimpleConnectionHandler.h
)
set(SOCKET_SOURCES
    src/socket/protocols/AuthorizingProtocol.cpp
    src/socket/protocols/AuthRequiredProtocol.cpp
    src/socket/protocols/PingingProtocol.cpp
    src/socket/protocols/PongingProtocol.cpp
    src/socket/protocols/ProtocolBase.cpp
    src/socket/protocols/ProtocolDecorator.cpp
    src/socket/protocols/ProtocolWithRequests.cpp
    src/socket/sessions/SessionBase.cpp
    src/socket/sessions/SSLSession.cpp
    src/socket/AsyncServer.cpp
    src/socket/BoostIOContext.cpp
    src/socket/BoostSSLContext.cpp
    src/socket/byte_order.cpp
    src/socket/connection_protocol.cpp
    src/socket/ConnectionStorage.cpp
    include/socket/Protocol.inl
    include/socket/Session.inl
    src/socket/SimpleConnectionHandler.cpp
)